apiVersion: apps/v1
kind: Deployment
metadata:
  name: ang-l-fw-be
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: ang-l-fw-be
  template:
    metadata:
      labels:
        app: ang-l-fw-be
    spec:
      containers:
      - name: ang-l-fw-be
        image: ang-l-fw/ang-l-fw-be:latest
        port:
          containerPort: 8000
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"  # Adjust resource requests and limits as needed